version: "3.8"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: techbro
    restart: unless-stopped

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - R_CLIENT_ID=${R_CLIENT_ID}
      - R_CLIENT_SECRET=${R_CLIENT_SECRET}
      - R_USERNAME=${R_USERNAME}
      - R_PASSWORD=${R_PASSWORD}
      - R_USER_AGENT=${R_USER_AGENT}
      - MONGODB_URI=mongodb://mongodb:27017
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - mongodb
    restart: unless-stopped
    command: ["python", "src/main.py"]

  worker:
    build: .
    environment:
      - R_CLIENT_ID=${R_CLIENT_ID}
      - R_CLIENT_SECRET=${R_CLIENT_SECRET}
      - R_USERNAME=${R_USERNAME}
      - R_PASSWORD=${R_PASSWORD}
      - R_USER_AGENT=${R_USER_AGENT}
      - MONGODB_URI=mongodb://mongodb:27017
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - mongodb
    restart: unless-stopped
    command:
      [
        "celery",
        "-A",
        "src.celery_app",
        "worker",
        "--loglevel=info",
        "--concurrency=2",
      ]

volumes:
  redis_data:
  mongodb_data:
